<?php

// Do not edit this file
// It is automatically generate during composer's install process

$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/podsbase.services.yml';

$settings['cache']['bins']['render'] = 'cache.backend.null';

$settings['cache']['bins']['page'] = 'cache.backend.null';

$settings['rebuild_access'] = TRUE;

if (file_exists($app_root . '/' . $site_path . '/settings.podsbase.php')) {
  include $app_root . '/' . $site_path . '/settings.podsbase.php';
}
